export { default as HeaderMain } from './Headermain'
export { default as Hero } from './Hero'
export { default as Skills } from './Skills'
export { default as Proyects } from './Proyects'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Services } from './Services'
export { default as WhyChooseUs } from './WhyChooseUs'
export { default as Pricing } from './Pricing'
export { default as CTASection } from './CTASection'
export { StatsSection } from './stats-section'

